kind: Endpoints
apiVersion: v1
metadata:
  name: router
subsets:
  - addresses:
      - ip: 192.168.188.1
    ports:
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.188.202
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router
spec:
  rules:
    - host: router.whiskeysierra.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  name: http
  tls:
    - hosts:
        - router.whiskeysierra.ddns.net
      secretName: router-whiskeysierra-ddns-net-tls
