apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
  - namespace.yaml
  - deployment.yaml
  - service-dns.yaml
  - service-http.yaml
  - ingress.yaml

configMapGenerator:
  - name: pihole-etc
    files:
      - adlists.list
      - regex.list
  - name: custom-dnsmasq
    files:
      - 02-custom.conf=dnsmasq.conf
  - name: pihole-env
    envs:
      - config.env
