apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service-dns.yaml
  - service-http.yaml
  - ingress.yaml

configMapGenerator:
  - name: pihole-etc
    files:
      - custom.list
  - name: pihole-env
    envs:
      - config.env

generators:
  - secret.yaml
