apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-view

resources:
  - namespace.yaml
  - git::https://codeberg.org/hjacobs/kube-web-view/deploy?ref=21.2.0
  - ingress.yaml

patchesStrategicMerge:
  - deployment-show-logs.yaml

patches:
  - path: patch-version.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1beta1
