apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unbound

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: unbound-config
    files:
      - unbound.conf
