kind: Service
apiVersion: v1
metadata:
  name: unbound
spec:
  # TODO clusterIP, so we have a fixed IP for CoreDNS's configuration
  selector:
    app: unbound
  ports:
    - name : dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
    - name : dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
